namespace Lubnan.Infrastructure.Persistence.Seed;

/// <summary>The shape of <c>places.seed.json</c>, generated by export-seed.mjs.</summary>
internal sealed record PlaceSeed(
    string Slug,
    string Region,
    string Category,
    int DisplayOrder,
    double Latitude,
    double Longitude,
    PlateSeed Plates,
    Dictionary<string, TranslationSeed> Translations,
    List<CalloutSeed> Callouts,
    List<FactSeed> Practical);

internal sealed record PlateSeed(string? Hero, string? Frame, string? Subject, string? Rail, string? Mosaic);

internal sealed record TranslationSeed(
    string Name,
    string? LocalName,
    string Note,
    string Standfirst,
    string Body);

internal sealed record CalloutSeed(double X, double Y, Dictionary<string, CalloutTextSeed> Text);

internal sealed record CalloutTextSeed(string Label, string Body);

internal sealed record FactSeed(Dictionary<string, FactTextSeed> Text);

internal sealed record FactTextSeed(string Label, string Value);
