import { readFileSync, writeFileSync } from 'node:fs';

/**
 * Turn the geoBoundaries ADM0 polygon for Lebanon into the ring the map
 * component draws.
 *
 * The hand-picked 26-point outline it replaces was a tracing, and it showed —
 * straight runs where the coast actually bends, and a southern border in the
 * wrong place. This keeps the real geometry and only drops points the eye
 * cannot resolve at the size the map is drawn.
 *
 * Source: geoBoundaries gbOpen LBN ADM0, public domain.
 */
const SRC = process.argv[2];
const OUT = 'data/lebanon-border.ts';
/** Degrees. ~250m at this latitude, well under one SVG pixel at our scale. */
const TOLERANCE = 0.0022;

const gj = JSON.parse(readFileSync(SRC, 'utf8'));
const geom = gj.features[0].geometry;
const rings = geom.type === 'Polygon' ? [geom.coordinates[0]] : geom.coordinates.map((p) => p[0]);
const ring = rings.sort((a, b) => b.length - a.length)[0];

/** Perpendicular distance from p to the segment ab. */
function dist(p, a, b) {
  const [px, py] = p;
  const [ax, ay] = a;
  const [bx, by] = b;
  const dx = bx - ax;
  const dy = by - ay;
  if (dx === 0 && dy === 0) return Math.hypot(px - ax, py - ay);
  const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)));
  return Math.hypot(px - (ax + t * dx), py - (ay + t * dy));
}

/** Douglas-Peucker. Keeps corners, drops points along straight runs. */
function simplify(pts, tol) {
  if (pts.length < 3) return pts;
  let maxD = 0;
  let idx = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const d = dist(pts[i], pts[0], pts[pts.length - 1]);
    if (d > maxD) {
      maxD = d;
      idx = i;
    }
  }
  if (maxD <= tol) return [pts[0], pts[pts.length - 1]];
  return [
    ...simplify(pts.slice(0, idx + 1), tol).slice(0, -1),
    ...simplify(pts.slice(idx), tol),
  ];
}

const simplified = simplify(ring, TOLERANCE).map(([lon, lat]) => [
  Number(lon.toFixed(4)),
  Number(lat.toFixed(4)),
]);

/**
 * Which points are coastline.
 *
 * The Mediterranean is west, so a point is coastal when nothing in the ring
 * sits meaningfully west of it at the same latitude. Computed rather than
 * eyeballed, so it stays right if the source data is ever swapped.
 */
const isCoast = simplified.map(([lon, lat]) => {
  const band = simplified.filter(([, la]) => Math.abs(la - lat) < 0.05);
  const lons = band.map(([lo]) => lo);
  const minLon = Math.min(...lons);
  const maxLon = Math.max(...lons);
  // Only meaningful where the country actually has width at this latitude.
  if (maxLon - minLon < 0.15) return false;
  return lon - minLon < 0.06;
});

/* Longest contiguous coastal run, treating the ring as circular and bridging
   short gaps — a headland or a river mouth briefly puts a point east of its
   band minimum, and without the bridge the run splits into a dozen fragments
   (the first version of this found 13 points instead of ~130). */
const n = simplified.length;
const GAP = 4;
let best = { start: 0, len: 0 };
for (let s = 0; s < n; s++) {
  if (!isCoast[s]) continue;
  let len = 0;
  let gap = 0;
  while (len < n) {
    if (isCoast[(s + len) % n]) gap = 0;
    else if (++gap > GAP) break;
    len++;
  }
  len -= gap;
  if (len > best.len) best = { start: s, len };
}

const coast = Array.from({ length: best.len }, (_, i) => simplified[(best.start + i) % n]);

const fmt = (pts) =>
  pts.map(([lo, la]) => `  [${lo}, ${la}],`).join('\n');

writeFileSync(
  OUT,
  `/**
 * Lebanon's national boundary and coastline.
 *
 * Source: geoBoundaries gbOpen LBN ADM0 (public domain), simplified with
 * Douglas-Peucker at ${TOLERANCE}° — roughly 250 m, comfortably under one
 * rendered pixel at the size the map is drawn.
 *
 * Generated by scripts/build-border.mjs. Do not edit by hand.
 */

/** Full ring, [lon, lat], ${simplified.length} points. */
export const BORDER: [number, number][] = [
${fmt(simplified)}
];

/** The Mediterranean edge only, drawn heavier. ${coast.length} points. */
export const COASTLINE: [number, number][] = [
${fmt(coast)}
];
`,
);

console.log(`ring       ${ring.length} -> ${simplified.length} points`);
console.log(`coastline  ${coast.length} points`);
const lons = simplified.map((p) => p[0]);
const lats = simplified.map((p) => p[1]);
console.log(
  `bounds     lon ${Math.min(...lons).toFixed(3)}..${Math.max(...lons).toFixed(3)}  lat ${Math.min(...lats).toFixed(3)}..${Math.max(...lats).toFixed(3)}`,
);
console.log(`wrote      ${OUT}`);
