// <auto-generated />
using System;
using System.Collections.Generic;
using Lubnan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lubnan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817225010_SavedPlaces")]
    partial class SavedPlaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lubnan.Domain.Community.CommunityPost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("PlaceSlug")
                        .HasMaxLength(80)
                        .HasColumnType("citext")
                        .HasColumnName("place_slug");

                    b.Property<string>("Plate")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("plate");

                    b.HasKey("Id")
                        .HasName("pk_community_posts");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_community_posts_author");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_community_posts_created_at");

                    b.HasIndex("PlaceSlug")
                        .HasDatabaseName("ix_community_posts_place");

                    b.ToTable("community_posts", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Community.PostComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_community_post_comments");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId", "CreatedAt")
                        .HasDatabaseName("ix_community_post_comments_post_created");

                    b.ToTable("community_post_comments", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Community.PostLike", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_community_post_likes");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_community_post_likes_post_user");

                    b.ToTable("community_post_likes", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Places.Callout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.Property<string>("_text")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_place_callouts");

                    b.HasIndex("PlaceId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_place_callouts_place_ordinal");

                    b.ToTable("place_callouts", null, t =>
                        {
                            t.HasCheckConstraint("ck_place_callouts_within_frame", "x >= 0 AND x <= 1 AND y >= 0 AND y <= 1");
                        });
                });

            modelBuilder.Entity("Lubnan.Domain.Places.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("region");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty<Dictionary<string, object>>("Coordinates", "Lubnan.Domain.Places.Place.Coordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Plates", "Lubnan.Domain.Places.Place.Plates#PlateSet", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Frame")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_frame");

                            b1.Property<string>("Hero")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_hero");

                            b1.Property<string>("Mosaic")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_mosaic");

                            b1.Property<string>("Rail")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_rail");

                            b1.Property<string>("Subject")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_subject");
                        });

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_places_slug");

                    b.HasIndex("Region", "DisplayOrder")
                        .HasDatabaseName("ix_places_published_region_order")
                        .HasFilter("published_at IS NOT NULL");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Places.PlaceTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("LocalName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("local_name");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("Standfirst")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("standfirst");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_place_translations");

                    b.HasIndex("PlaceId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_place_translations_place_locale");

                    b.ToTable("place_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_place_translations_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Lubnan.Domain.Places.PracticalFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("_text")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_place_facts");

                    b.HasIndex("PlaceId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_place_facts_place_ordinal");

                    b.ToTable("place_facts", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Saved.SavedPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("PlaceSlug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("citext")
                        .HasColumnName("place_slug");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_places");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_places_user");

                    b.HasIndex("UserId", "PlaceSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_places_user_slug");

                    b.ToTable("saved_places", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Users.AccountEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("IpHash")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ip_hash");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account_events");

                    b.HasIndex("ActorId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_account_events_actor_time")
                        .HasFilter("actor_id IS NOT NULL");

                    b.HasIndex("UserId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_account_events_user_time");

                    b.ToTable("account_events", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnonymisedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("anonymised_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<int>("FailedSignInCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_sign_in_count");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LastSignedInAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_signed_in_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("PurgeAfter")
                        .HasColumnType("timestamptz")
                        .HasColumnName("purge_after");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("suspended_at");

                    b.Property<DateTimeOffset?>("SuspendedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("suspended_until");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PurgeAfter")
                        .HasDatabaseName("ix_users_pending_purge")
                        .HasFilter("purge_after IS NOT NULL AND anonymised_at IS NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EndReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("IpHash")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ip_hash");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_used_at");

                    b.Property<Guid?>("ReplacedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_user_sessions_family");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_user_sessions_active")
                        .HasFilter("ended_at IS NULL");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Users.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<string>("Payload")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("payload");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_tokens");

                    b.HasIndex("UserId");

                    b.HasIndex("TokenHash", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("ix_user_tokens_hash_purpose");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Lubnan.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Community.CommunityPost", b =>
                {
                    b.HasOne("Lubnan.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_community_posts_author_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Community.PostComment", b =>
                {
                    b.HasOne("Lubnan.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_comments_author_id");

                    b.HasOne("Lubnan.Domain.Community.CommunityPost", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_comments_post_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Community.PostLike", b =>
                {
                    b.HasOne("Lubnan.Domain.Community.CommunityPost", null)
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_likes_post_id");

                    b.HasOne("Lubnan.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_likes_user_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Places.Callout", b =>
                {
                    b.HasOne("Lubnan.Domain.Places.Place", null)
                        .WithMany("Callouts")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_callouts_place_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Places.PlaceTranslation", b =>
                {
                    b.HasOne("Lubnan.Domain.Places.Place", null)
                        .WithMany("Translations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_translations_place_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Places.PracticalFact", b =>
                {
                    b.HasOne("Lubnan.Domain.Places.Place", null)
                        .WithMany("PracticalFacts")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_facts_place_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Saved.SavedPlace", b =>
                {
                    b.HasOne("Lubnan.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_places_user_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Users.AccountEvent", b =>
                {
                    b.HasOne("Lubnan.Domain.Users.User", null)
                        .WithMany("AccountEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_events_user_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Users.UserSession", b =>
                {
                    b.HasOne("Lubnan.Domain.Users.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_user_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Users.UserToken", b =>
                {
                    b.HasOne("Lubnan.Domain.Users.User", null)
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_user_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Community.CommunityPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Lubnan.Domain.Places.Place", b =>
                {
                    b.Navigation("Callouts");

                    b.Navigation("PracticalFacts");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Lubnan.Domain.Users.User", b =>
                {
                    b.Navigation("AccountEvents");

                    b.Navigation("Sessions");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
