// <auto-generated />
using System;
using System.Collections.Generic;
using Lubnan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lubnan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lubnan.Domain.Places.Callout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.Property<string>("_text")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_place_callouts");

                    b.HasIndex("PlaceId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_place_callouts_place_ordinal");

                    b.ToTable("place_callouts", null, t =>
                        {
                            t.HasCheckConstraint("ck_place_callouts_within_frame", "x >= 0 AND x <= 1 AND y >= 0 AND y <= 1");
                        });
                });

            modelBuilder.Entity("Lubnan.Domain.Places.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("region");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty<Dictionary<string, object>>("Coordinates", "Lubnan.Domain.Places.Place.Coordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Plates", "Lubnan.Domain.Places.Place.Plates#PlateSet", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Frame")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_frame");

                            b1.Property<string>("Hero")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_hero");

                            b1.Property<string>("Mosaic")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_mosaic");

                            b1.Property<string>("Rail")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_rail");

                            b1.Property<string>("Subject")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("plate_subject");
                        });

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_places_slug");

                    b.HasIndex("Region", "DisplayOrder")
                        .HasDatabaseName("ix_places_published_region_order")
                        .HasFilter("published_at IS NOT NULL");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Places.PlaceTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("LocalName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("local_name");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("Standfirst")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("standfirst");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_place_translations");

                    b.HasIndex("PlaceId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_place_translations_place_locale");

                    b.ToTable("place_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_place_translations_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Lubnan.Domain.Places.PracticalFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("_text")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_place_facts");

                    b.HasIndex("PlaceId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_place_facts_place_ordinal");

                    b.ToTable("place_facts", (string)null);
                });

            modelBuilder.Entity("Lubnan.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Lubnan.Domain.Places.Callout", b =>
                {
                    b.HasOne("Lubnan.Domain.Places.Place", null)
                        .WithMany("Callouts")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_callouts_place_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Places.PlaceTranslation", b =>
                {
                    b.HasOne("Lubnan.Domain.Places.Place", null)
                        .WithMany("Translations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_translations_place_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Places.PracticalFact", b =>
                {
                    b.HasOne("Lubnan.Domain.Places.Place", null)
                        .WithMany("PracticalFacts")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_facts_place_id");
                });

            modelBuilder.Entity("Lubnan.Domain.Places.Place", b =>
                {
                    b.Navigation("Callouts");

                    b.Navigation("PracticalFacts");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
